### PR TITLE
feanil/heroku stack upgrade

### PR DESCRIPTION
**Pull request by feanil**
- build: Update to python 3.11
- chore: Run make upgrade.

### CODE REVIEW

**Review by nedbat — APPROVED** [review]

**Comment by UsamaSadiq** [comment]
@feanil  Have we finalised to start upgrading the repos to `Python 3.11`? 
The reusable workflow being used in all the repos only runs with `Python 3.8`. If we are going to start upgrading to `Python 3.11`, we'll need to update the reusable workflow for accepting custom python version as argument to run requirements upgrade job against. 
example automated PR making this change: https://github.com/openedx/openedxstats/pull/199

**Comment by feanil** [comment]
@UsamaSadiq ah, good point.  These services run in Heroku, where a 3.8 environment is much less supported so I upgrade them to 3.11, this should not impact other schedules but yes, we should update the re-usable workflows so it's possible to pass in a different python version if people want to use it with newer versions of python.

**Comment by feanil** [comment]
@UsamaSadiq I created https://github.com/openedx/.github/pull/81 and https://github.com/openedx/openedxstats/pull/200 to resolve this, can you review them when you have a sec?

**Comment by feanil** [comment]
FYI, those two PRs merged but we found one more issue: https://github.com/openedx/testeng-ci/pull/361

**Comment by feanil** [comment]
Ok, all the issues have been resolved, here's the working upgrade PR: https://github.com/openedx/openedxstats/pull/202

**Pull request merged**
